
import conec.connector;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mir Lutfur Rahman
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage("images/a2i.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane2 = new java.awt.ScrollPane();
        popupMenu1 = new java.awt.PopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cell = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        popupMenu1.setLabel("popupMenu1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ডিজিটাল উদ্ভাবনী মেলা - ২০১৬ ইংরেজী"); // NOI18N
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1360, 760));

        panel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 630));

        javax.swing.ImageIcon img=new javax.swing.ImageIcon("Images/title.png");
        jLabel1.setIcon(img);

        javax.swing.ImageIcon img2=new javax.swing.ImageIcon("Images/footer.jpg");
        jLabel2.setIcon(img2);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 40)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("E-Lottery Software");

        jLabel4.setFont(new java.awt.Font("Sakkal Majalla", 1, 35)); // NOI18N
        jLabel4.setText("  Visitor Records:");

        jLabel5.setFont(new java.awt.Font("Euphemia", 1, 19)); // NOI18N
        jLabel5.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Euphemia", 1, 19)); // NOI18N
        jLabel6.setText("Cell Number:");

        name.setToolTipText("Enter your fullname.");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        cell.setToolTipText("Enter your cell number.");
        cell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("( Ex. Mr. Abcd )");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("( Ex. 01xxxxxxxxx )");

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.setToolTipText("Save data.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total entries:");

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        int i=0;
        connector ob4=new connector();
        String query4 = "Select * FROM data";
        try {

            ob4.rs = ob4.stmt.executeQuery(query4);
            i=0;
            while (ob4.rs.next()) {
                i++;
            }
            ob4.con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Check Database Connection.","Notice", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
        jLabel10.setText(i+"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(401, 401, 401)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(name)
                                    .addComponent(cell, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(711, 711, 711))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(301, 301, 301))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cell, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jMenu1.setText("Entry Records");
        jMenu1.setToolTipText("See all the visitor entries.");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jMenu2.setText("Reset Status");
        jMenu2.setToolTipText("Reset all draw status.");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jMenu5.setText("Admin Panel");
        jMenu5.setToolTipText("Enter into the administrative system.");
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jMenu7.setText("Developer Info");
        jMenu7.setToolTipText("View the developer details.");
        jMenu7.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu7MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jMenu6.setText("Exit");
        jMenu6.setToolTipText("Terminate the program.");
        jMenu6.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu6MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(758, 758, 758)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(602, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(870, 870, 870)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s1=name.getText().trim();
        String s2=cell.getText().trim();
        if(s1.equals("") || s2.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please fill up perfectly !!!","Notice", JOptionPane.WARNING_MESSAGE);
        }
        else if(s2.length()!=11)
        {
            JOptionPane.showMessageDialog(this, "Invalid mobile number !!! ("+s2.length()+"digits).","Notice", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            try
            {
                long k=Long.parseLong(s2);
                connector ob1=new connector();
                int fl=0;
                String query = "Select * FROM data";
                try {

                        ob1.rs = ob1.stmt.executeQuery(query);
                        String contact = "";
                        while (ob1.rs.next()) {

                                contact = ob1.rs.getString(2);
                                if(s2.equals(contact))
                                    fl=1;
                        }
                        ob1.con.close();
                } catch (SQLException e) {
                        e.printStackTrace();
                }
                if(fl==1)
                {
                    JOptionPane.showMessageDialog(this, "Sorry you are cell number is already registered.","Notice", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    ob1=new connector();
                    query="INSERT INTO data " + "VALUES ('"+s1+"', '"+s2+"', '0')";
		            try {

		              ob1.stmt.executeUpdate(query);
		              ob1.con.close();
		            }

		            catch(SQLException e) {
                                e.printStackTrace();
                            }

                        JOptionPane.showMessageDialog(this, "Hi! "+s1+"\nCell Number: "+s2+"\n"+"Thanks for join with us.","Notice", JOptionPane.INFORMATION_MESSAGE);
                        this.hide();
                        index ob=new index();
                        ob.show();
                }    
            }catch(NumberFormatException ae)
            {
                JOptionPane.showMessageDialog(this, "Invalid mobile number !!! (Digits can't be a character).","Notice", JOptionPane.WARNING_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellActionPerformed
        // TODO add your handling code here:
        String s1=name.getText().trim();
        String s2=cell.getText().trim();
        if(s1.equals("") || s2.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please fill up perfectly !!!","Notice", JOptionPane.WARNING_MESSAGE);
        }
        else if(s2.length()!=11)
        {
            JOptionPane.showMessageDialog(this, "Invalid mobile number !!! ("+s2.length()+"digits).","Notice", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            try
            {
                long k=Long.parseLong(s2);
                connector ob1=new connector();
                int fl=0;
                String query = "Select * FROM data";
                try {

                        ob1.rs = ob1.stmt.executeQuery(query);
                        String contact = "";
                        while (ob1.rs.next()) {

                                contact = ob1.rs.getString(2);
                                if(s2.equals(contact))
                                    fl=1;
                        }
                        ob1.con.close();
                } catch (SQLException e) {
                        e.printStackTrace();
                }
                if(fl==1)
                {
                    JOptionPane.showMessageDialog(this, "Sorry you are cell number is already registered.","Notice", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    ob1=new connector();
                     query="INSERT INTO data " + "VALUES ('"+s1+"', '"+s2+"', '0')";
		            try {

		              ob1.stmt.executeUpdate(query);
		              ob1.con.close();
		            }

		            catch(SQLException e) {
                                e.printStackTrace();
                            }
                            
                        JOptionPane.showMessageDialog(this, "Hi! "+s1+"\nCell Number: "+s2+"\n"+"Thanks for join with us.","Notice", JOptionPane.INFORMATION_MESSAGE);
                        this.hide();
                        index ob=new index();
                        ob.show();
                }
            }catch(NumberFormatException ae)
            {
                JOptionPane.showMessageDialog(this, "Invalid mobile number !!! (Digits can't be a character).","Notice", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_cellActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        String s1=name.getText().trim();
        String s2=cell.getText().trim();
        if(s1.equals("") || s2.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please fill up perfectly !!!","Notice", JOptionPane.WARNING_MESSAGE);
        }
        else if(s2.length()!=11)
        {
            JOptionPane.showMessageDialog(this, "Invalid mobile number !!! ("+s2.length()+"digits).","Notice", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            try
            {
                long k=Long.parseLong(s2);
                connector ob1=new connector();
                int fl=0;
                String query = "Select * FROM data";
                try {

                        ob1.rs = ob1.stmt.executeQuery(query);
                        String contact = "";
                        while (ob1.rs.next()) {

                                contact = ob1.rs.getString(2);
                                if(s2.equals(contact))
                                    fl=1;
                        }
                        ob1.con.close();
                } catch (SQLException e) {
                        e.printStackTrace();
                }
                if(fl==1)
                {
                    JOptionPane.showMessageDialog(this, "Sorry you are cell number is already registered.","Notice", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    ob1=new connector();
                    query="INSERT INTO data " + "VALUES ('"+s1+"', '"+s2+"', '0')";
                                try {

                                  ob1.stmt.executeUpdate(query);
                                  ob1.con.close();
                                }

                                catch(SQLException e) {
                                    e.printStackTrace();
                                }

                    JOptionPane.showMessageDialog(this, "Hi! "+s1+"\nCell Number: "+s2+"\n"+"Thanks for join with us.","Notice", JOptionPane.INFORMATION_MESSAGE);
                    this.hide();
                    index ob=new index();
                    ob.show();
                }
            }catch(NumberFormatException ae)
                    {
                        JOptionPane.showMessageDialog(this, "Invalid mobile number !!! (Digits can't be a character).","Notice", JOptionPane.WARNING_MESSAGE);
                    }
            
        }
    }//GEN-LAST:event_nameActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
        entries ob=new entries();
        this.hide();
        ob.show();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu6MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu6MenuSelected
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu6MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        // TODO add your handling code here:
            
                connector ob5=new connector();
                String query = "Select * FROM data";
                try {

                        ob5.rs = ob5.stmt.executeQuery(query);
                        String contact = "",name="",cell="";
                        while (ob5.rs.next()) {

                                name=ob5.rs.getString(1);
                                cell=ob5.rs.getString(2);
                                contact = ob5.rs.getString(3);
                                
                                if(contact.equals("1"))
                                {
                                    
                                     connector ob2=new connector();        
                                    String query2 = "update data set status='0' where cell = '"+cell+"'";
                                    try {

                                      ob2.stmt.executeUpdate(query2);
                                      ob2.con.close();
                                    }

                                    catch(SQLException e) {
                                        e.printStackTrace();
                                    }
                                }
                        }
                        ob5.con.close();
                } catch (SQLException e) {
                        e.printStackTrace();
                }
                JOptionPane.showMessageDialog(this, "Status reseted successfully.","Notice", JOptionPane.WARNING_MESSAGE);
                this.hide();
                index ob=new index();
                ob.show();
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu7MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu7MenuSelected
        // TODO add your handling code here:
        developer ob=new developer();
        this.hide();
        ob.show();
    }//GEN-LAST:event_jMenu7MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
        // TODO add your handling code here:
        admin ob=new admin();
        this.hide();
        ob.show();
    }//GEN-LAST:event_jMenu5MenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cell;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField name;
    private java.awt.Panel panel1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.ScrollPane scrollPane2;
    // End of variables declaration//GEN-END:variables
}
